name: Test Latest PS Gallery Version

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 6 * * *'

jobs:
  Run-URLScan-Pester-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install URLScan.io Module
        shell: pwsh
        run: |
          Write-Host "Installing URLScan.io Module.."
          Install-Module URLScan.io -Force -Confirm:$false

      - name: Run Pester Tests
        shell: pwsh
        env:
          NUGET_KEY: ${{ secrets.URLSCAN_IO }}
        run: |
          $PesterConfig = New-PesterConfiguration
          $PesterConfig.Run.Path = './Tests/'
          $PesterConfig.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $PesterConfig