name: Run URLScan.io Pester Tests

on: workflow_dispatch

jobs:
  Run-URLScan-Pester-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pester Module
        shell: pwsh
        run: |
          Install-Module Pester -Force -Confirm:$false

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Write-Host "Importing URLScan.io Module.."
          Import-Module './Modules/URLScan.io/URLScan.io.psd1'

          $PesterConfig = New-PesterConfiguration
          $PesterConfig.Run.Path = './Tests/'
          $PesterConfig.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $PesterConfig